import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fdfaf3",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  imgLogo: {
    width: 410,
    height: 400,
    borderBottomLeftRadius: 70,
    borderBottomRightRadius: 70,
    borderColor: "#e8c986",
    borderWidth: 5,
  },
  tituloLogin: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#2e1504",
    marginTop: 10,
  },
  nome: {
    fontSize: 15,
    color: "#2e1504",
    marginTop: 20,
    fontWeight: 400,
    paddingRight: 255,
  },
  inputContainerNome: {
    width: 300,
    height: 50,
    borderRadius: 5,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: "center",
    top: 10,
  },
  inputNome: {
    flex: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    color: "#000",
  },
  inputContainerEmail: {
    width: 300,
    height: 50,
    borderRadius: 5,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: "center",
    top: 20,
  },
    inputEmail: {
        flex: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        color: "#000",
    },
    email: {
        fontSize: 15,
        color: "#2e1504",
        marginTop: 20,
        fontWeight: 400,
        paddingRight: 255,
        top: 8,
    },
    inputContainerSenha: {
    width: 300,
    height: 50,
    borderRadius: 5,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: "center",
    top: 30,
  },
    inputSenha: {
        flex: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        color: "#000",
    },
    senha: {
        fontSize: 15,
        color: "#2e1504",
        marginTop: 20,
        fontWeight: 400,
        paddingRight: 255,
        top:16,
    },
    
});
export default styles;
