import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fdfaf3",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  imgLogoFundo: {
    width: 410,
    height: 420,
    borderBottomLeftRadius: 70,
    borderBottomRightRadius: 70,
    borderColor: "#e8c986",
    borderWidth: 5,
    top: -20,
  },
  imgLogo: {
    width: 350,
    height: 350,
    marginTop: -700,
  },
  nome: {
    fontSize: 15,
    color: "#2e1504",
    marginTop: 20,
    fontWeight: 400,
    paddingRight: 255,
  },
  inputContainerNome: {
    width: 300,
    height: 50,
    borderRadius: 5,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: "center",
    top: 5,
  },
  inputNome: {
    flex: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    color: "#000",
  },
  inputContainerEmail: {
    width: 300,
    height: 50,
    borderRadius: 5,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: "center",
    top: 5,
  },
    inputEmail: {
        flex: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        color: "#000",
    },
    email: {
        fontSize: 15,
        color: "#2e1504",
        marginTop: 20,
        fontWeight: 400,
        paddingRight: 255,
    },
    inputContainerSenha: {
    width: 300,
    height: 50,
    borderRadius: 5,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: "center",
    top: 5,
  },
    inputSenha: {
        flex: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        color: "#000",
    },
    senha: {
        fontSize: 15,
        color: "#2e1504",
        marginTop: 20,
        fontWeight: 400,
        paddingRight: 255,
    },
    botaoEntrar: {
        width: 300,
        height: 45,
        borderRadius: 6,
        backgroundColor: "#e8c986",
        justifyContent: "center",
        alignItems: "center",
        top: 85,
    },
    textoBotaoEntrar: {
        fontSize: 20,
        color: "white",
        fontWeight:700,
    },
    botaoCadastrese: {
        width: 300,
        height: 45,
        borderRadius: 6,
        backgroundColor: "#411d06",
        justifyContent: "center",
        alignItems: "center",
        top: 109,
    },
    textoBotaoCadastrese: {
        fontSize: 20,
        color: "white",
        fontWeight:700,
    },
    
});
export default styles;
